# Generated by Django 4.2.10 on 2026-02-04 18:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Category name (e.g., 'Electronics', 'Smartphones')",
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly name (auto-generated from name)",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed category description"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome icon class (e.g., 'fas fa-mobile-alt')",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this category is visible in the store",
                    ),
                ),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category (leave empty for top-level categories)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="shop.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["ordering", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Product name", max_length=255
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly product name",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        help_text="Stock Keeping Unit (required if no variants)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Product brand/manufacturer",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Full product description (supports HTML)"
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="Brief one-line description for listings",
                        max_length=500,
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Base price (used if no variants)",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost price for profit calculations",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total stock (aggregated from variants if they exist)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether product is available for sale",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether to feature on homepage",
                    ),
                ),
                (
                    "is_bestseller",
                    models.BooleanField(
                        default=False, help_text="Whether product is a bestseller"
                    ),
                ),
                (
                    "is_new",
                    models.BooleanField(
                        default=False, help_text="Whether product is newly added"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO title (leave empty to use name)",
                        max_length=255,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, help_text="SEO meta description", max_length=500
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="SEO keywords (comma-separated)",
                        max_length=500,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average rating (0-5)",
                        max_digits=3,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "review_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of reviews"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Product category",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="shop.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "sku",
                    models.CharField(
                        db_index=True,
                        help_text="Variant-specific SKU",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Variant price",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Variant cost price",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=0, help_text="Available stock for this variant"
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Variant attributes (e.g., {"size": "XL", "color": "Red"})',
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Set as default variant for product"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this variant is available",
                    ),
                ),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Display order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Parent product",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Variant",
                "verbose_name_plural": "Product Variants",
                "ordering": ["ordering", "sku"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "image",
                    models.ImageField(
                        help_text="Product image", upload_to="products/%Y/%m/%d/"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alt text for accessibility and SEO",
                        max_length=255,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Set as primary/featured image",
                    ),
                ),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Display order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product (required)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shop.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific variant (optional - leave empty for all variants)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="images",
                        to="shop.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "ordering": ["ordering"],
            },
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["product", "is_active"], name="shop_produc_product_27d2af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["is_default", "product"], name="shop_produc_is_defa_ada2ef_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together={("product", "sku")},
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product", "is_primary"], name="shop_produc_product_58a9da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product", "variant"], name="shop_produc_product_4ae14b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productimage",
            unique_together={("product", "image")},
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "category"], name="shop_produc_is_acti_6b3eaa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_featured", "is_active"],
                name="shop_produc_is_feat_a70478_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["brand", "is_active"], name="shop_produc_brand_1fcf96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-created_at"], name="shop_produc_created_ddfb00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_active", "ordering"], name="shop_catego_is_acti_bb665f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["parent", "is_active"], name="shop_catego_parent__114883_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("slug", "parent")},
        ),
    ]
